baseURL = 'https://plaintextdecap.netlify.app/'
languageCode = 'en-US'

[taxonomies]
  category = 'categories'

[permalinks]
  categories = '/:section/:slug'

[params]
  dateFormat = 'Jan 2, 2006'

[menus]
[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menus.main]]
  name = 'Writing & Podcast'
  pageRef = '/blog'
  weight = 20
[[menus.main]]
  name = 'Philosophy'
  pageRef = '/philosophy'
  weight = 30
[[menus.main]]
  name = 'Team'
  pageRef = '/team'
  weight = 40
[[menus.main]]
  name = 'Contact'
  pageRef = '/learn-more'
  weight = 50

[[menus.secondary]]
  name = 'Newsletter'
  pageRef = '#'
  weight = 60