# using git as backend store
backend:
  name: git-gateway
  branch: main
media_folder: "/static/media" # Folder where user uploaded files should go
public_folder: "/media"
editor:
  preview: false

# Allow local visit
# You need to run at the root of the project `npx netlify-cms-proxy-server`
local_backend: true

# collections configuration
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    slug: '{{slug}}'
    create: true
    sort: 'publish_date'
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime"}
      - { label: "Featured Image", name: "image", widget: "image", required: false}
      - { label: "Categories", name: "Category", widget: "string" }
      - { label: ".", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
    - name: "philosophy"
      label: "Philosophy"
      file: "content/philosophy.md"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Body", name: "body", widget: "markdown" }