# using git as backend store
backend:
  name: git-gateway
  branch: main
media_folder: "/static/media" # Folder where user uploaded files should go
public_folder: "/media"
editor:
  preview: false

# Allow local visit
# You need to run at the root of the project `npx netlify-cms-proxy-server`
local_backend: true

# collections configuration
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    slug: '{{slug}}'
    create: true
    sort: 'date'
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime"}
      - { label: "Featured Image", name: "image", widget: "image", required: false}
      - { label: "Categories", name: "Category", widget: "string" }
      - { label: ".", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Philsophy Page"
        name: "philsophy"
        file: "content/philsophy.md"
        folder: "content"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: ".", name: "body", widget: "markdown" }
      - label: "Team Page"
        name: "team"
        file: "content/team.md"
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Position, name: position, widget: string}
          - {label: Photo, name: photo, widget: image}
      - label: "Contact Page"
        name: "lean-more"
        file: "content/lean-more.md"
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Address, name: address, widget: string}