# using git as backend store
backend:
  name: git-gateway
  branch: main
media_folder: "/static/media" # Folder where user uploaded files should go
public_folder: "/media"
editor:
  preview: false

# Allow local visit
# You need to run at the root of the project `npx netlify-cms-proxy-server`
local_backend: true

# collections configuration
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    path: 'content/{{slug}}'
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime"}
      - { label: "Featured Image", name: "image", widget: "image", required: false}
      - { label: "Categories", name: "Category", widget: "string" }
      - { label: ".", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    file: "content"
    folder: "content"
    path: "{{slug}}/index"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cover Image", name: "image", widget: "image" , media_folder: "/static/media" , public_folder: "/media" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }