# using git as backend store
backend:
  name: git-gateway
  branch: main
media_folder: "/static/images" # Folder where user uploaded files should go
public_folder: "/images"
editor:
  preview: false

# Allow local visit
# You need to run at the root of the project `npx netlify-cms-proxy-server`
local_backend: true

# collections configuration
collections:
  - name: "blog"
    label: "Blog Post"
    folder: "content/blog"
    slug: '{{slug}}'
    create: true
    sort: 'date'
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date"}
      - { label: "Featured Image", name: "image", widget: "image", required: false}
      - { label: "Categories", name: "categories", widget: "select", options: ["Podcast", "Market Commentary", "Insights"] }
      - { label: "Author", name: "author", widget: "select", options: ["Phil Bonello", "Andrés García", "Fran Oliva-Velez"] }
      - { label: ".", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/philosophy/index.md"
        label: "Philosophy"
        name: "philosophy"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: ".", name: "body", widget: "markdown" }
      - file: "content/team/index.md"
        label: "Team"
        name: "team"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "Sections",
              name: "sections",
              widget: object,
              fields: [
                {
                  label: type,
                  name: type,
                  widget: 'list',
                  allow_add: false,
                  collapsed: false,
                  field: {
                    label: 'Profile',
                    name: 'profile',
                    widget: 'list',
                    fields: [
                      { label: 'Role', name: 'role', widget: 'text' },
                      { label: 'Name', name: 'name', widget: 'text' },
                      { label: 'image', name: 'imageUrl', widget: 'image' },
                      { label: 'X', name: 'x', widget: 'text' },
                      { label: 'LinkedIn', name: 'in', widget: 'text' },
                    ]
                  }
                },
              ],
            }
      - file: "content/disclaimer/index.md"
        label: "Disclaimer"
        name: "disclaimer"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "Sections",
              name: "sections",
              widget: object,
              fields: [
                { label: Text, name: text, widget: 'markdown' }
              ]
            }
      - file: "content/learn-more/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "Sections",
              name: "sections",
              summary: "Address, Email and Mail Destination Settings",
              allow_add: false,
              widget: list,
              fields: [
                { label: Address Label, name: titleAddress, widget: string },
                { label: Address, name: address, widget: string },
                { label: Email Label, name: titleEmail, widget: string },
                { label: Email Address, name: email, widget: string },
                {
                  label: Form,
                  name: form,
                  widget: object,
                  collapsed: true,
                  summary: Your contact form is sent to this email address.,
                  fields: [
                    { label: Destination Email, name: destination, widget: string }
                  ]
                },
              ]
            }